@startuml

actor Actor
participant onCreate
Actor -> onCreate

participant setupBillingClient
onCreate -> setupBillingClient

create participant Billing << (C,#ADD1B2) >>
setupBillingClient -> Billing : new

create participant BillingClient << (C,#ADD1B2) >>
Billing -> BillingClient : build()

BillingClient -> BillingClient: startConnection

@enduml
